# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: effdef3b90f8513ee69ad98ba28c37a1703b8b68a29f3d36801f3d2299e5eec5dafa370a1187511752ed77580ae755a95df5495acdd5822c7c89c373110fef37

test:
  secret_key_base: d32d293e2bd6652c0cbd7189a6080842c8aa4c3db8218b64d0473a513d419caa063c4165ee71faf434a85211d1aa6613de5031b018ecaed1b8483456f7fa4817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
